name: GitHub Clone Count Update Everyday

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: gh login
        run: echo "${{ secrets.SECRET_TOKEN }}" | gh auth login --with-token

      - name: parse latest clone count
        run: |
          curl --user "${{ github.actor }}:${{ secrets.SECRET_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/traffic/clones \
            > clone.json

      - name: create gist and download previous count
        id: set_id
        run: |
          if gh secret list | grep -q "GIST_ID"
          then
              echo "GIST_ID found"
              echo "GIST=${{ secrets.GIST_ID }}" >> $GITHUB_OUTPUT
              curl --user "${{ github.actor }}:${{ secrets.SECRET_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/gists/${{ secrets.GIST_ID }} \
              > previous_clone.json
          else
              echo "GIST_ID not found"
              gh gist create clone.json
          fi

      - name: update clone.json
        run: |
          curl https://raw.githubusercontent.com/MShawon/github-clone-count-badge/master/main.py > main.py
          python3 main.py

      - name: Update gist with latest count
        run: |
          content=$(sed 's/\\/\\\\/g' clone.json | sed 's/"/\\"/g' | sed 's/$/\\n/' | tr -d '\n')
          curl -X PATCH \
          --user "${{ github.actor }}:${{ secrets.SECRET_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/gists/${{ steps.set_id.outputs.GIST }} \
          -d "{\"files\":{\"clone.json\":{\"content\":\"$content\"}}}"
